# Generated by Django 3.1.1 on 2020-09-28 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('file_path', models.FileField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('active_status', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
