# Generated by Django 3.1.1 on 2020-12-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201227_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'patient'), (2, 'doctor'), (3, 'developer')]),
        ),
    ]
